version: '3.7'
services:
  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'postgres1234'
      POSTGRES_DB: db_bitacora_prod

  admin:
    image: adminer
    ports:
      - 8080:8080